name: my_app
description: A new Flutter project.

environment:
  sdk: '>=3.0.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
    
  supabase_flutter: ^2.0.0   # Supabase যুক্ত করো
  url_launcher: ^6.1.15
  flutter_lints: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
